name: "Git Semantic Version"
description: "Determines version of a repo based on git history"
branding:
  icon: "layers"
  color: "blue"
inputs:
  branch:
    description: "The branch name"
    required: true
    default: "master"
  tag_prefix:
    description: "The prefix to use to identify tags"
    required: false
    default: "v"
  major_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a major (breaking) change"
    required: true
    default: "(MAJOR)"
  minor_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a minor (feature) change"
    required: true
    default: "(MINOR)"
  main_format: "${major}.${minor}.${patch}"
    description: "Pattern to use when formatting main part of output version"
    required: true
    default: "${major}.${minor}.${patch}dev${increment}"
    # A string to determine the format of the version output
  increment_format: "${increment}"
    description: "Pattern to use when formatting main part of output version"
    required: true
    default: "${major}.${minor}.${patch}dev${increment}"
    # A string to determine the format of the version output
  increment_delimiter: "dev"
    description: "Pattern to use when formatting main part of output version"
    required: true
    default: "${major}.${minor}.${patch}dev${increment}"
  change_path:
    description: "Path to check for changes. If any changes are detected in the path the 'changed' output will true. Enter multiple paths separated by spaces."
    required: false
outputs:
  major:
    description: "Current major number"
  minor:
    description: "Current minor number"
  patch:
    description: "Current patch number"
  increment:
    description: "An additional value indicating the number of commits for the current version"
  version:
    description: "The version result, in the format {major}.{minor}.{patch}"
  changed:
    description: "Indicates whether there was a change since the last version if change_path was specified. If no change_path was specified this value will always be false."
  tag:
    description: "The version result with the tag prefix, in the format {tag_prefix}{major}.{minor}.{patch}"
runs:
  using: "node12"
  main: "dist/index.js"
